version: "3.7"

services:
#  BACKEND
  redis:
    image: redis:alpine
    restart: always
    container_name: redis-diplom
    ports:
      - "6379:6379"
    networks:
      - redis_celery_network

  celery:
    build: ./backend/django-app/
    restart: unless-stopped
    container_name: celery-diplom
    command:
      - celery
      - -A
      - diplom.celery_app
      - worker
      - -B
      - --loglevel=INFO
      - --concurrency=14
    volumes:
      - ./backend/django-app/:/app/backend/
    depends_on:
      - redis
      - django
      - postgres_db
      - django-migrate
    networks:
      - postgres_network
      - redis_celery_network


  django-migrate:
    container_name: django-migrate-diplom
    build: ./backend/django-app/
    command:
      - sh
      - -c
      - "python manage.py migrate"
    networks:
      - postgres_network
    depends_on:
      - redis

  django:
    container_name: django-app-diplom
    build: ./backend/django-app/
    volumes:
      - ./backend/django-app/:/app/backend/
      - static:/app/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres_db
      - django-migrate
    networks:
      - postgres_network
      - nginx-network

  postgres_db:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - ./backend/django-app/diplom/.env
    container_name: postgres_db-diplom
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    expose:
      - 5432


  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5454:5454/tcp"
    env_file:
      - ./backend/django-app/diplom/.env
    depends_on:
      - postgres_db
    expose:
      - 5432
    container_name: pgadmin-diplom
    networks:
      - postgres_network
      - nginx-network

  dashboard:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=9000
    ports:
      - "9000:9000"
    container_name: chvetochek-diplom
    depends_on:
      - celery
    networks:
      - redis_celery_network
      - nginx-network

#    FRONTEND
  react:
    container_name: react-diplom
    build: ./frontend/
    volumes:
      - './frontend/:/app/frontend/'
      - '/app/frontend/node_modules'
    ports:
      - "3000:5173"
    expose:
      - 5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - nginx-network

# WEB SERVER
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/backend/static
    depends_on:
      - react
      - django
    networks:
      - nginx-network

volumes:
  postgresdata:
  static:

networks:
  postgres_network:
    name: default-pg-network
    driver: bridge

  redis_celery_network:
    name: nw-redis-celery

  nginx-network:
    name: nw-nginx
    driver: bridge