# Generated by Django 4.1.5 on 2023-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ('name',), 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='is_comp',
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Кабинет'),
        ),
    ]
