# Generated by Django 4.1.5 on 2023-01-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Кабинет')),
                ('is_comp', models.BooleanField(default=False, verbose_name='Компьютерный кабинет?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется?')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=1000, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется?')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название пары')),
                ('require_comp', models.BooleanField(default=False, verbose_name='Нужен компьютерный класс?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется?')),
                ('cabinets', models.ManyToManyField(to='app.cabinet', verbose_name='Кабинеты')),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teacher', verbose_name='Препод')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название группы')),
                ('max_day', models.IntegerField(default=4, verbose_name='Максимум пар за день')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется?')),
                ('lessons', models.ManyToManyField(to='app.lesson', verbose_name='Пары')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
